import images from "./imageData";

export const items = [
  // Mobiles
  {
    id: 1,
    category: 'mobiles',
    title: "Apple iPhone 14 Pro Max",
    imgSrc: images[1],
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'Apple iPhone 14 Pro Max (256 GB) - Deep Purple with A16 Bionic chip and Dynamic Island.',
    price: '149999',
  },
  {
    id: 2,
    category: 'mobiles',
    title: "Samsung Galaxy S23 Ultra",
    imgSrc: images[2],
    amazonLink: 'https://amzn.to/44MiYi6',
    description: 'Samsung Galaxy S23 Ultra (12GB RAM, 512GB) - Phantom Black with 200MP Camera.',
    price: '124999',
  },
  {
    id: 3,
    category: 'mobiles',
    title: "Google Pixel 7 Pro",
    imgSrc: images[3],
    amazonLink: 'https://amzn.to/3r6XJtv',
    description: 'Google Pixel 7 Pro with Tensor G2 chip and 120Hz AMOLED display.',
    price: '84999',
  },
  {
    id: 4,
    category: 'mobiles',
    title: "OnePlus 11 5G",
    imgSrc: images[4],
    amazonLink: 'https://amzn.to/3O6M8Uv',
    description: 'OnePlus 11 5G (16GB RAM, 256GB) - Eternal Green with Hasselblad Camera.',
    price: '61999',
  },
  {
    id: 5,
    category: 'mobiles',
    title: "Vivo X90 Pro",
    imgSrc: images[5],
    amazonLink: 'https://amzn.to/3EZeQaC',
    description: 'Vivo X90 Pro 5G with ZEISS optics and MediaTek Dimensity 9200 processor.',
    price: '84999',
  },
  {
    id: 6,
    category: 'mobiles',
    title: "Realme GT 3",
    imgSrc: images[6],
    amazonLink: 'https://amzn.to/3r9Rvhm',
    description: 'Realme GT 3 (16GB RAM, 256GB) - Flash White with 240W SuperVOOC charge.',
    price: '42999',
  },
  {
    id: 7,
    category: 'mobiles',
    title: "Xiaomi 13 Pro",
    imgSrc: images[7],
    amazonLink: 'https://amzn.to/3ReKTGh',
    description: 'Xiaomi 13 Pro 5G (12GB RAM, 256GB) with Leica Professional camera system.',
    price: '79999',
  },
  {
    id: 8,
    category: 'mobiles',
    title: "Oppo Find N2 Flip",
    imgSrc: images[8],
    amazonLink: 'https://amzn.to/3EzeQaC',
    description: 'Oppo Find N2 Flip - Compact foldable phone with 50MP camera and AMOLED display.',
    price: '89999',
  },
  {
    id: 9,
    category: 'mobiles',
    title: "Samsung Galaxy Z Fold 5",
    imgSrc: images[9],
    amazonLink: 'https://amzn.to/3PbY9Lp',
    description: 'Samsung Galaxy Z Fold 5 (12GB RAM, 512GB) - Phantom Blue with Snapdragon 8 Gen 2.',
    price: '154999',
  },
  {
    id: 10,
    category: 'mobiles',
    title: "Poco F5",
    imgSrc: images[10],
    amazonLink: 'https://amzn.to/44MiYi6',
    description: 'Poco F5 (8GB RAM, 256GB) with Snapdragon 7+ Gen 2 and AMOLED display.',
    price: '29999',
  },
  {
    id: 11,
    category: 'mobiles',
    title: "Nothing Phone (2)",
    imgSrc: images[11],
    amazonLink: 'https://amzn.to/3r9Rvhm',
    description: 'Nothing Phone (2) - Innovative transparent design with Glyph interface.',
    price: '44999',
  },
  {
    id: 12,
    category: 'mobiles',
    title: "iQOO Neo 7 Pro",
    imgSrc: images[12],
    amazonLink: 'https://amzn.to/3PbY9Lp',
    description: 'iQOO Neo 7 Pro (8GB RAM, 256GB) with Snapdragon 8+ Gen 1 and 120W charging.',
    price: '37999',
  },
  {
    id: 13,
    category: 'mobiles',
    title: "Motorola Edge 40",
    imgSrc: images[13],
    amazonLink: 'https://amzn.to/3EzeQaC',
    description: 'Motorola Edge 40 with curved pOLED display and MediaTek Dimensity 8020 chipset.',
    price: '29999',
  },
  {
    id: 14,
    category: 'mobiles',
    title: "Infinix Zero Ultra",
    imgSrc: images[14],
    amazonLink: 'https://amzn.to/3ReKTGh',
    description: 'Infinix Zero Ultra 5G with 200MP camera and 180W Thunder Charge.',
    price: '32999',
  },
  {
    id: 15,
    category: 'mobiles',
    title: "Redmi Note 12 Pro",
    imgSrc: images[15],
    amazonLink: 'https://amzn.to/3PbY9Lp',
    description: 'Redmi Note 12 Pro+ (12GB RAM, 256GB) - Stunning AMOLED display with 120Hz refresh rate.',
    price: '26999',
  },

  // Laptops (15 more products here...)


    // Laptops
    
      {
        id: 16,
        category: "laptops",
        title: "Apple MacBook Air M2",
        imgSrc: images[16],
        amazonLink: "https://amzn.to/3PbUjVh",
        description:
          "Apple MacBook Air with M2 chip, 13.6-inch Liquid Retina Display, 8GB RAM, and 256GB SSD.",
        price: "114999",
      },
      {
        id: 17,
        category: "laptops",
        title: "Dell XPS 13 Plus",
        imgSrc: images[17],
        amazonLink: "https://amzn.to/3R8TQPf",
        description:
          "Dell XPS 13 Plus (12th Gen Intel Core i7, 16GB RAM, 512GB SSD) with InfinityEdge Display.",
        price: "149999",
      },
      {
        id: 18,
        category: "laptops",
        title: "HP Spectre x360",
        imgSrc: images[18],
        amazonLink: "https://amzn.to/3YuqTz8",
        description:
          "HP Spectre x360 2-in-1 Laptop with Intel Evo Core i7, 16GB RAM, and 1TB SSD.",
        price: "134999",
      },
      {
        id: 19,
        category: "laptops",
        title: "Asus ROG Zephyrus G14",
        imgSrc: images[19],
        amazonLink: "https://amzn.to/3Pb6UNg",
        description:
          "Asus ROG Zephyrus G14 with Ryzen 9 5900HS, 16GB RAM, 1TB SSD, and NVIDIA RTX 3060.",
        price: "129999",
      },
      {
        id: 20,
        category: "laptops",
        title: "Lenovo ThinkPad X1 Carbon",
        imgSrc: images[20],
        amazonLink: "https://amzn.to/3Re7YkA",
        description:
          "Lenovo ThinkPad X1 Carbon Gen 10 with 12th Gen Intel Core i7, 16GB RAM, and 512GB SSD.",
        price: "159999",
      },
      {
        id: 21,
        category: "laptops",
        title: "Microsoft Surface Laptop 5",
        imgSrc: images[21],
        amazonLink: "https://amzn.to/3PbWWNf",
        description:
          "Microsoft Surface Laptop 5 with Intel Core i5, 8GB RAM, and 256GB SSD, Platinum finish.",
        price: "99999",
      },
      {
        id: 22,
        category: "laptops",
        title: "Acer Swift 3 OLED",
        imgSrc: images[22],
        amazonLink: "https://amzn.to/3O6TAvq",
        description:
          "Acer Swift 3 OLED Laptop with 12th Gen Intel Core i7, 16GB RAM, and 1TB SSD.",
        price: "87999",
      },
      {
        id: 23,
        category: "laptops",
        title: "Razer Blade 15",
        imgSrc: images[23],
        amazonLink: "https://amzn.to/3r9YTqM",
        description:
          "Razer Blade 15 Gaming Laptop with NVIDIA GeForce RTX 3070 Ti, Intel i7, and 1TB SSD.",
        price: "199999",
      },
      {
        id: 24,
        category: "laptops",
        title: "HP Pavilion 15",
        imgSrc: images[24],
        amazonLink: "https://amzn.to/3Yt4MjJ",
        description: "HP Pavilion 15 Laptop with AMD Ryzen 7, 16GB RAM, and 512GB SSD.",
        price: "62999",
      },
      {
        id: 25,
        category: "laptops",
        title: "LG Gram 17",
        imgSrc: images[25],
        amazonLink: "https://amzn.to/3O5uXuV",
        description:
          "LG Gram 17 Ultra-Lightweight Laptop with 17-inch QHD+ Display and 16GB RAM.",
        price: "124999",
      },
      {
        id: 26,
        category: "laptops",
        title: "Asus ZenBook Duo 14",
        imgSrc: images[26],
        amazonLink: "https://amzn.to/44Y6SXM",
        description:
          "Asus ZenBook Duo 14 with Dual Screen, Intel i7, 16GB RAM, and 1TB SSD.",
        price: "99999",
      },
      {
        id: 27,
        category: "laptops",
        title: "MSI Creator Z16",
        imgSrc: images[27],
        amazonLink: "https://amzn.to/3ReXhUt",
        description:
          "MSI Creator Z16 Professional Laptop with RTX 3060, Intel i7, and 1TB SSD.",
        price: "179999",
      },
      {
        id: 28,
        category: "laptops",
        title: "Dell Inspiron 16 Plus",
        imgSrc: images[28],
        amazonLink: "https://amzn.to/3O6TQJe",
        description: "Dell Inspiron 16 Plus Laptop with Intel i5, 8GB RAM, and 512GB SSD.",
        price: "75999",
      },
      {
        id: 29,
        category: "laptops",
        title: "Huawei MateBook X Pro",
        imgSrc: images[29],
        amazonLink: "https://amzn.to/3ReJjNg",
        description:
          "Huawei MateBook X Pro with 3K touchscreen display, Intel i7, and 1TB SSD.",
        price: "149999",
      },
      {
        id: 30,
        category: "laptops",
        title: "Asus TUF Dash F15",
        imgSrc: images[30],
        amazonLink: "https://amzn.to/3r9YTqF",
        description:
          "Asus TUF Dash F15 Gaming Laptop with Intel i7, NVIDIA RTX 3070, and 512GB SSD.",
        price: "109999",
      },
    
    

  
  // Tablets (15 more products here...)

 
    // Tablets
    {
      id: 31,
      category: 'tablets',
      title: "Apple iPad Pro 12.9-inch",
      imgSrc: images[31],
      amazonLink: 'https://amzn.to/3FbKlX1',
      description: 'Apple iPad Pro 12.9-inch with M2 Chip, Liquid Retina XDR Display, 128GB Storage, Wi-Fi.',
      price: '109999',
    },
    {
      id: 32,
      category: 'tablets',
      title: "Samsung Galaxy Tab S9 Ultra",
      imgSrc: images[32],
      amazonLink: 'https://amzn.to/3ReF9XP',
      description: 'Samsung Galaxy Tab S9 Ultra 14.6-inch AMOLED Display, Snapdragon 8 Gen 2, 256GB Storage, S Pen.',
      price: '119999',
    },
    {
      id: 33,
      category: 'tablets',
      title: "Microsoft Surface Pro 9",
      imgSrc: images[33],
      amazonLink: 'https://amzn.to/3r9T2hL',
      description: 'Microsoft Surface Pro 9 with Intel Core i5, 8GB RAM, and 256GB SSD, Platinum Finish.',
      price: '99999',
    },
    {
      id: 34,
      category: 'tablets',
      title: "Lenovo Tab P11 Pro Gen 2",
      imgSrc: images[34],
      amazonLink: 'https://amzn.to/3YvgL9X',
      description: 'Lenovo Tab P11 Pro Gen 2 with 11.2-inch OLED Display, 6GB RAM, and 128GB Storage.',
      price: '49999',
    },
    {
      id: 35,
      category: 'tablets',
      title: "Xiaomi Pad 6 Pro",
      imgSrc: images[35],
      amazonLink: 'https://amzn.to/44P2xWz',
      description: 'Xiaomi Pad 6 Pro with Snapdragon 8+ Gen 1, 8GB RAM, and 256GB Storage, 11-inch Display.',
      price: '39999',
    },
    {
      id: 36,
      category: 'tablets',
      title: "Huawei MatePad Pro 12.6",
      imgSrc: images[36],
      amazonLink: 'https://amzn.to/3PbXtRj',
      description: 'Huawei MatePad Pro 12.6-inch OLED Display, Kirin 9000E, 8GB RAM, and 256GB Storage.',
      price: '74999',
    },
    {
      id: 37,
      category: 'tablets',
      title: "Amazon Fire HD 10",
      imgSrc: images[37],
      amazonLink: 'https://amzn.to/3YvNQsJ',
      description: 'Amazon Fire HD 10 Tablet with 10.1-inch Full HD Display, 3GB RAM, and 64GB Storage.',
      price: '11999',
    },
    {
      id: 38,
      category: 'tablets',
      title: "Samsung Galaxy Tab A7",
      imgSrc: images[38],
      amazonLink: 'https://amzn.to/3Yy2YNA',
      description: 'Samsung Galaxy Tab A7 with 10.4-inch Display, Snapdragon 662, 3GB RAM, and 64GB Storage.',
      price: '17999',
    },
    {
      id: 39,
      category: 'tablets',
      title: "Realme Pad X",
      imgSrc: images[39],
      amazonLink: 'https://amzn.to/3PdWZfA',
      description: 'Realme Pad X with 11-inch Display, Qualcomm Snapdragon 695, 6GB RAM, and 128GB Storage.',
      price: '25999',
    },
    {
      id: 40,
      category: 'tablets',
      title: "Google Pixel Tablet",
      imgSrc: images[40],
      amazonLink: 'https://amzn.to/3YxuVW6',
      description: 'Google Pixel Tablet with Tensor G2 Chip, 11-inch Display, and 128GB Storage.',
      price: '59999',
    },
    {
      id: 41,
      category: 'tablets',
      title: "Apple iPad Mini 6",
      imgSrc: images[41],
      amazonLink: 'https://amzn.to/3r8J6Lh',
      description: 'Apple iPad Mini 6 with A15 Bionic Chip, 8.3-inch Liquid Retina Display, and 64GB Storage.',
      price: '49999',
    },
    {
      id: 42,
      category: 'tablets',
      title: "Samsung Galaxy Tab S7 FE",
      imgSrc: images[42],
      amazonLink: 'https://amzn.to/3r6XQUh',
      description: 'Samsung Galaxy Tab S7 FE with 12.4-inch Display, Snapdragon 750G, and 64GB Storage.',
      price: '35999',
    },
    {
      id: 43,
      category: 'tablets',
      title: "Lenovo Yoga Tab 13",
      imgSrc: images[43],
      amazonLink: 'https://amzn.to/3FbWVWw',
      description: 'Lenovo Yoga Tab 13 with Snapdragon 870, 8GB RAM, and 128GB Storage, Dolby Vision Display.',
      price: '62999',
    },
    {
      id: 44,
      category: 'tablets',
      title: "OnePlus Pad",
      imgSrc: images[44],
      amazonLink: 'https://amzn.to/3RdNRJz',
      description: 'OnePlus Pad with Dimensity 9000, 8GB RAM, and 128GB Storage, 11.61-inch Display.',
      price: '37999',
    },
    {
      id: 45,
      category: 'tablets',
      title: "Asus ROG Flow Z13",
      imgSrc: images[45],
      amazonLink: 'https://amzn.to/3PbVNHq',
      description: 'Asus ROG Flow Z13 Gaming Tablet with Intel i7, NVIDIA RTX 3050, and 512GB SSD.',
      price: '159999',
    },
  
  


];
